---
abstract: 'efficient wiki browsing and editing'
author:
  - 'Chris Dent <cdent@peermore.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TiddlyWeb-Wikrad
no_index:
  directory:
    - t
    - inc
requires:
  Class::Field: 0
  Curses::UI: 0.95
  JSON: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Readonly: 0
  URI: 0
  YAML: 0
version: 0.9
