--- #YAML:1.0
name:                TiddlyWeb-Wikrad
version:             0.8
abstract:            efficient wiki browsing and editing
license:             ~
author:              
    - Chris Dent <cdent@peermore.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Field:                  0
    Curses::UI:                    0.95
    JSON:                          0
    JSON::XS:                      0
    LWP::UserAgent:                0
    Readonly:                      0
    URI:                           0
    YAML:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
